### ISSUE TITLE
WiFiManager

### ISSUE THREAD

**Issue by kentaylor** [SensorsIot/IOTAppstory.com#4]
You [mentioned](https://github.com/tzapu/WiFiManager/issues/249#issuecomment-262973669) that you are using WiFiManager in the IOT-Appstore and I was curious to see how. I can't see a reference to it here so I guess that version of the source hasn't been checked in yet?

In particular I didn't understand 

> The handover is done with a variable in RTC memory.

as I'm confused as to what handover would be necessary.

Looking at the [source](https://github.com/SensorsIot/IOT-Appstore/blob/master/IotAppStoreLoaderV1/IotAppStoreLoaderV1.ino) I can see that you [read](https://github.com/SensorsIot/IOT-Appstore/blob/master/IotAppStoreLoaderV1/IotAppStoreLoaderV1.ino#L122) the WiFi credentials from your own flash store and then use them in a call to WiFi.begin. 

There is no need to store WiFi credentials as a call to WiFi.begin will store them in a region of flash used only by the Espressif library. Then, when the device reboots it starts the WiFi connection using those credentials before the Arduino sketch is started. The Arduino sketch will start about 400ms after boot and [about 320ms](https://github.com/tzapu/WiFiManager/issues/221#issuecomment-262404263) after the millis timer starts. There is no need to call WiFi.begin again until you want to change the WiFi parameters and if you do call WiFi.begin with credentials that match those stored it does nothing useful.

**Comment by SensorsIot** [comment]
Thanks for the comments. I will review my sketches and remove the WiFi.begin(). I had some issues with "lost" passwords in the Espressif environment. This is, why I included them also in my EEPROM space. If it does not help, it does not hurt.
I used your fork for the newest infrastructure. The library is great and does exactly, what I need! The only thing is, that it does not "save" after save. But it works. Thank you for your contribution.
I separated the "config" part completely from the sketch part, because I had some issues if I used webserver also in the sketch. Like that, I do not need to care about changes on your side and the sketch is "cleaner".
